tomitribe/tribestream-api-registry

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_singleselect.ts, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_header.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/component_singleselect.jade
- new disableActions attribute
=> REG-337 - fix select field change bug

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_header.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_header.jade
=> REG-344 description field highlight

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details.jade
=> REG-315 disable save btn until title and version are set

tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_header.jade
REG-357 #194 Remove the "Description" label
=> REG-357 #194 Remove the "Description" label

tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints.ts
REG-364 #145 Support "escape" in the search text field
=> REG-364 #145 Support "escape" in the search text field

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_diff.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_common.ts, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_history.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_header.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_history.jade
=> Reg 360 diff tool with headers

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details.sass
=> REG-362 Stabilize the Version field while editing

tribestream-api-registry-webapp/src/main/java/org/tomitribe/tribestream/registryng/repository/DuplicatedSwaggerException.java, tribestream-api-registry-webapp/src/main/java/org/tomitribe/tribestream/registryng/repository/Repository.java, tribestream-api-registry-webapp/src/main/java/org/tomitribe/tribestream/registryng/resources/ApplicationResource.java, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints.ts, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details.jade, tribestream-api-registry-webapp/src/test/java/org/tomitribe/tribestream/registryng/resources/ApplicationResourceTest.java
catch transactional exception at the server side, show error message at the client side and hide application link until the application is properly created
=> REG-354 protect create application page from creating duplicated application

tribestream-api-registry-webapp/src/main/static/assets/styles/_component_markdown.sass
REG-372 Fix the position of the Markdown edit bar
=> REG-372 Fix the position of the Markdown edit bar

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_list.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_filter.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_list_application.jade
=> [WIP] REG-356 Home page - update h1, h2, h3, h4 sizing

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_markdown.ts, tribestream-api-registry-webapp/src/main/static/assets/styles/_component_markdown.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/component_markdown_help.jade
No visible control to close the help window in the markdown editor
=> REG-383 No visible control to close the help window in the markdown editor

tribestream-api-registry-webapp/src/main/java/org/tomitribe/tribestream/registryng/resources/EndpointResource.java, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts, tribestream-api-registry-webapp/src/test/java/org/tomitribe/tribestream/registryng/resources/EndpointResourceTest.java
demo here: https://youtu.be/0petfm2Eink
=> REG-399 show a message similar to the one we use in application details

tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_list_application.jade, tribestream-api-registry-webapp/src/test/static/test_filters.ts
Demo here: https://youtu.be/viNOmbODaYE
=> REG-400 remove filter from template and use it only in the endpoint link call

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details_history.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_history.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details_history.jade
Demo here: https://youtu.be/cix3-hczD4c
=> REG-360 make application details show the same labels in the diff panel as we do in the endpoint details page

tribestream-api-registry-webapp/src/main/static/assets/styles/_component_confirm_btn.sass
REG-409 Can edit some fields with delete confirmation dialog being show
=> REG-409 Can edit some fields with delete confirmation dialog being shown

tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_resource_information.jade
- Rename "API Version" label to "Endpoint Version"
=> REG-413 Ambiguos meaning of "API VERSION" on the Endpoint detail.

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_markdown.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details.jade
Demo here: https://youtu.be/vTqIwO5C1bM
=> REG-406 application details historic item reload

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_singleselect.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_textfield.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_tip.ts, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_application_details.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_header.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_component_singleselect.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/app.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_application_details.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_header.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/component_singleselect.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/component_singleselect_selected.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/component_text.jade
Demo here: https://youtu.be/vXDNh-Mlp3w
=> REG-407 making mandatory fields visible in the application details and endpoint details pages

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_multiselect.ts, tribestream-api-registry-webapp/src/main/static/assets/templates/component_multiselect_available.jade
Demo here: https://youtu.be/5JUVsDsuFIs
=> REG-363 do not select on hover

tribestream-api-registry-webapp/src/main/static/assets/scripts/_components_singleselect.ts, tribestream-api-registry-webapp/src/main/static/assets/styles/_component_multiselect.sass, tribestream-api-registry-webapp/src/main/static/assets/styles/_component_singleselect.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/component_singleselect_available.jade, tribestream-api-registry-webapp/src/main/static/assets/templates/component_singleselect_selected.jade
Demo here: https://youtu.be/jDDgbxJGgOs
=> REG-363 multiselect transparency issue and single select issue

tribestream-api-registry-webapp/src/main/java/org/tomitribe/tribestream/registryng/repository/Repository.java, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts
Demo here: https://youtu.be/6rbDtl7TijI
=> REG-424 removing null parameters

tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_header.sass
demo here https://youtu.be/rTNM2pOXMx8
=> REG-373 endpoint details placeholder text with fontweight 700

tribestream-api-registry-webapp/src/main/static/assets/scripts/_main.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints.ts, tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts
Demo here https://youtu.be/7hJcFJpWZyQ
=> REG-385 forcing no cache for rest calls - caching IE tends to cache it

tribestream-api-registry-webapp/src/main/static/assets/scripts/endpoints_details.ts, tribestream-api-registry-webapp/src/main/static/assets/styles/_app_endpoints_details_parameters.sass, tribestream-api-registry-webapp/src/main/static/assets/templates/app_endpoints_details_parameters.jade
Demo here: https://youtu.be/vfq6rxp2O1M
=> REG-426 new default values; set type as NA if placement is body;
